### PR TITLE
Fix memory usage computation for stl::unordered_set

### PR DESCRIPTION
**Pull request by gssiyankai**

### CODE REVIEW

**Comment by lemire** [comment]
I don't think that's correct. It is true that we pass ``std::unordered_set`` a memory allocator with type ``uint32_t`` when instantiating the template. So you'd think that the ``std::unordered_set`` would allocate arrays of ``uint32_t``, but if I look at the code, what I actually realize is that the code calls rebind... to instead allocate arrays of something called ``Hash_node``...

```
    // rebind allocator to type U
    template <class U> struct rebind {
        typedef MemoryCountingAllocator<U> other;
    };
```

**Comment by gssiyankai** [comment]
Oh... right... thanks for pointing that out. It makes more sense to me now: there is a dedicated data structure behind the unordered_set that is taking more space that uint32_t.
More precisely, the underlying data structure is a hash table composed of n buckets:

- Each bucket starts with a base node that just contains a pointer to value node (a bucket is a singly linked list). So each base node needs 64 bits. 
- A value node wraps a hashcode, the uint32_t and a pointer to the next value node so it needs 128 bits (for memory alignment)

This means that each value needs 192 bits at best. This lower bound is usually not reached because of the rehash policy that doubles the number of buckets when the load factor gets too high. One way to get rid of most of the unnecessary buckets is to rehash explicitly with the required number of buckets after creating the bitmaps. Note the the same kind of resizing is done with the vector:
https://github.com/RoaringBitmap/CBitmapCompetition/blob/master/src/stl_vector_benchmarks.cpp#L136

**Comment by gssiyankai** [comment]
With my last commit, memory usage is ~195 bits per value.

**Comment by lemire** [comment]
Fantastic.

**Pull request merged**
